
// Generated by the mtime code generator.  DO NOT EDIT!
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

package mtime.ml.crawler.service.iface;
import mtime.ml.crawler.service.dto.InvokeCrawlerDto.*;

	/**
	 * 调用爬取个性网服务
	 * mscgenVersion: 0.4.3
	**/
public interface InvokeCrawlerService {

	
	/**
	 * 调用一次爬取个性网服务
	 * 
	 * @return
	**/
	InvokeCrawlerResponse invokeCrawler();
	
}
	